export class User {
    UserID: number;
    UserType: string;
    UserEmail: string;
    Password: string;
    NamePrefix: string;
    NameFirst: string;
    NameMiddle: string;
    NameLast: string;
    NameSuffix: string;
    JobTitle: string;
    HomeAddress: string;
    WorkPhone: number;
    MobilePhone: number;
    HomePhone: number;
    DateOfBirth: Date;
    FeaturesEnabled: boolean;
    UserPhoto: string;
    HeightInches: number;
    WeightPounds: number;
    BloodType: string;
    AllergyInfo: string;
    DietInfo: string;
    clinic?: any;
    statusList?: [];
    feedbackList?: [];
    events?: [];
    ratings?: [];
}